"""
LLM Response Parser
Extracts code blocks and explanation text from unstructured LLM output.
"""
import re
from typing import Tuple, Optional


CODE_BLOCK_PATTERN = re.compile(
    r"```(?:\w+)?\s*\n(.*?)```",
    re.DOTALL,
)


def extract_code_and_explanation(response: str) -> Tuple[str, str]:
    """
    Parse an LLM response into (code, explanation).

    Handles responses with one or more fenced code blocks. The first block is
    treated as the patch; remaining text becomes the explanation.
    """
    if not response or not response.strip():
        return "", "Empty LLM response."

    matches = CODE_BLOCK_PATTERN.findall(response)
    if matches:
        code = matches[0].strip()
        # Remove all code blocks to isolate explanation prose
        explanation = CODE_BLOCK_PATTERN.sub("", response).strip()
        if not explanation:
            explanation = "Fix generated by Ollama AI engine based on error context."
        return code, explanation

    # No code fences — treat entire response as code if it looks like source
    stripped = response.strip()
    if _looks_like_code(stripped):
        return stripped, "AI generated patch based on error report pattern."

    return "", stripped or "Could not extract code from LLM response."


def _looks_like_code(text: str) -> bool:
    """Heuristic: response is likely source code rather than prose."""
    code_indicators = ("def ", "class ", "function ", "import ", "const ", "var ", "public ", "return ")
    first_lines = text.splitlines()[:5]
    return any(
        any(ind in line for ind in code_indicators)
        for line in first_lines
    )


def strip_language_prefix(code: str, language: Optional[str] = None) -> str:
    """Remove accidental language tag left on the first line of extracted code."""
    if not code:
        return code
    first_line = code.splitlines()[0].strip().lower()
    known_tags = {
        "python", "javascript", "typescript", "java", "go", "cpp", "c++",
        "csharp", "c#", "ruby", "rust", "php", "bash", "shell", "json",
    }
    if first_line in known_tags or (language and first_line == language.lower()):
        return "\n".join(code.splitlines()[1:]).strip()
    return code.strip()
